{% set version = "1.6-5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-arules
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/arules_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/arules/arules_{{ version }}.tar.gz
  sha256: 9ba0674eeb1fd5c54a894dfd0ab1e4a7c282fd796f8e9ff62667b34d91759b2d

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-matrix >=1.2_0
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-matrix >=1.2_0

test:
  commands:
    - $R -e "library('arules')"           # [not win]
    - "\"%R%\" -e \"library('arules')\""  # [win]

about:
  home: https://github.com/mhahsler/arules
  license: GPL-3
  summary: Provides the infrastructure for representing, manipulating and analyzing transaction data and patterns (frequent itemsets and association rules). Also
    provides C implementations of the association mining algorithms Apriori and Eclat.  See Christian Borgelt (2012) <doi:10.1002/widm.1074>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: arules
# Version: 1.6-4
# Date: 2019-08-27
# Title: Mining Association Rules and Frequent Itemsets
# Authors@R: c(person("Michael", "Hahsler", role = c("aut", "cre", "cph"), email = "mhahsler@lyle.smu.edu"), person("Christian", "Buchta", role = c("aut", "cph")), person("Bettina", "Gruen", role = c("aut", "cph")), person("Kurt", "Hornik", role = c("aut", "cph")), person("Ian", "Johnson", role = c("ctb", "cph")), person("Christian", "Borgelt", role = c("ctb", "cph")))
# Description: Provides the infrastructure for representing, manipulating and analyzing transaction data and patterns (frequent itemsets and association rules). Also provides C implementations of the association mining algorithms Apriori and Eclat.  See Christian Borgelt (2012) <doi:10.1002/widm.1074>.
# Classification/ACM: G.4, H.2.8, I.5.1
# URL: https://github.com/mhahsler/arules
# BugReports: https://github.com/mhahsler/arules/issues
# Depends: R (>= 3.4.0), Matrix (>= 1.2-0)
# Imports: stats, methods, graphics, utils
# Suggests: pmml, XML, arulesViz, testthat
# License: GPL-3
# Copyright: The source code for Apriori and Eclat was obtained from http://www.borgelt.net/ and is Copyright (C) 1996-2003 Christian Borgelt. All other code is Copyright (C) Michael Hahsler, Christian Buchta, Bettina Gruen and Kurt Hornik.
# NeedsCompilation: yes
# Packaged: 2019-08-28 17:01:41 UTC; hahsler
# Author: Michael Hahsler [aut, cre, cph], Christian Buchta [aut, cph], Bettina Gruen [aut, cph], Kurt Hornik [aut, cph], Ian Johnson [ctb, cph], Christian Borgelt [ctb, cph]
# Maintainer: Michael Hahsler <mhahsler@lyle.smu.edu>
# Repository: CRAN
# Date/Publication: 2019-08-29 04:40:06 UTC
