# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "mehe3zQsiXJxAOB+S30Pum5UbferEfwPVj1fFanTC68IQ1SCacHPst64s+Eg1Q6BKwCVrFzqLlcPaGvcHJXNcjIV/v6YxDm1gbSifkjVC+IcjlBaho2BmUlMgNjEwfyEqKdQDTjNEERMtCmU1oqf1cO9cuDs3/XZyCWRakk635UYJWP7z2cuHgN8vtjCB3PSTJb2Amu4qkNdd20nHddjISM+6sWbdETV+1QQKgZPU7zIqZ+a8vBWQLNSCdmxhwmaPfBCl5Fc0zDmryJocRXuj/Kr5x/PHVx1FkW2HU1jGL4st96OLTvGp3nqfmzV47wllGM/baG01iPVncvibkVhr9L2wCEPOeb/I1E35dkU3fImlgYyTZI71f6LyDeIBYCVaJfkAQF8YbqVZrWCIlXG1436O9F/ENhT+niY7yFOTebf8ArbfReikkV4TRFdL0+EFWJTja6MBNJ06miLKvQDc/0fQOX/VQQ/oD//9/Cf6es9KGT8IrwR48EmvIHZU+Li6t2DtgwRRIltPHrAoa+/AoA/qOzZQFo+s3Sg3TPWNGq36m5+3FX/KRpXpu8+9whpnliF+zLp0JOD/IKiH5mU8O4zPZGRR0+8Z8IfPhcTXPmsty9l9U0MUfk0WfIUhwn9VZUk5Y1zJYawyd8EndjGw4tCkXRfl9r4vvRdq83IiXA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml