appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: v7Sdg8XCVHmAbOuIf+nNkdaa3GDeX0uuP0NKrdqev6/PdcYsJZ2nT6qhETtoW1Ft1+vdiSvzoPp6YAm8PbOm/dU2+xXDDq4XWTwdFmBXu5ytHPoDnw4//FQHNPqofXXmab9pCmUSOMUJm/8yY0oUczzSRUEwfDriHavce3giJXObuaYubzksmQaoQro0paHRgvN4ykZNAdvtqsCYO8koGnOE2ZBbhfFFrzLcZ9zo6mlJ0p7DDdOTkxIHWAKLIJWFlzxKlYuSSu81tSkjvIxWwQX8+i7VQ6GyufrU8F7uWi6+T/lJKbozdoc5jzTw2fFyBmC5iFNsvkHZ9DMwoZm4yneGLYyaULF9KHISEhDZCMez4ok7XBjfp36KrTPoCDpiiUxYmzXswYiecELybCqI5QUQwN6kxjm/olJxzfBwP3/aTmHeOMJ9803pCR2FyL5K7tmg4kvgiFhOYHpZbW83N2tWcWiGCtTVfnH4RT21/Kg8OYK5eP8ayAlmfkStU+vO4SJvC4N4mkqeRHEzt6Usl00m8m2gcxTEekroz5viGRSSoF9b2bNorukDRsA7cqh6RBJjEt8eojGsIOzsf7s0SnkULHt16J5PvbVLcY8Ytmw9ARYq+dwDQiKXWVhiMcQoNRDzDMdX2b8PM4NBZ3oy5QpwD4x7vmADY6Fz3+SIHwA=}
