travis:
  secure:
    BINSTAR_TOKEN: mehe3zQsiXJxAOB+S30Pum5UbferEfwPVj1fFanTC68IQ1SCacHPst64s+Eg1Q6BKwCVrFzqLlcPaGvcHJXNcjIV/v6YxDm1gbSifkjVC+IcjlBaho2BmUlMgNjEwfyEqKdQDTjNEERMtCmU1oqf1cO9cuDs3/XZyCWRakk635UYJWP7z2cuHgN8vtjCB3PSTJb2Amu4qkNdd20nHddjISM+6sWbdETV+1QQKgZPU7zIqZ+a8vBWQLNSCdmxhwmaPfBCl5Fc0zDmryJocRXuj/Kr5x/PHVx1FkW2HU1jGL4st96OLTvGp3nqfmzV47wllGM/baG01iPVncvibkVhr9L2wCEPOeb/I1E35dkU3fImlgYyTZI71f6LyDeIBYCVaJfkAQF8YbqVZrWCIlXG1436O9F/ENhT+niY7yFOTebf8ArbfReikkV4TRFdL0+EFWJTja6MBNJ06miLKvQDc/0fQOX/VQQ/oD//9/Cf6es9KGT8IrwR48EmvIHZU+Li6t2DtgwRRIltPHrAoa+/AoA/qOzZQFo+s3Sg3TPWNGq36m5+3FX/KRpXpu8+9whpnliF+zLp0JOD/IKiH5mU8O4zPZGRR0+8Z8IfPhcTXPmsty9l9U0MUfk0WfIUhwn9VZUk5Y1zJYawyd8EndjGw4tCkXRfl9r4vvRdq83IiXA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
